# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtuser',
            name='uid',
            field=models.TextField(default='0cac5336529540929895f5aec058cde1'),
        ),
    ]
