# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wiseturn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=wiseturn.models.hex_uuid, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUB', 'Submitted'), ('PEN', 'Pending'), ('REV', 'Under Review'), ('APP', 'Approved')], default='SUB', max_length=3)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiseturn.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
