# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0002_institutionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAdmin',
            fields=[
                ('wtuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiseturn.Institution')),
            ],
            options={
                'abstract': False,
            },
            bases=('wiseturn.wtuser',),
        ),
    ]
