# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0002_auto_20181216_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wtuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wtuser',
            name='uid',
            field=models.CharField(default='cdff52d9d164423aac33fa8d5a75329f', max_length=255),
        ),
    ]
