# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wiseturn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0003_auto_20181216_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dli_number', models.TextField(null=True, unique=True)),
                ('founded', models.IntegerField()),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('cost_of_living', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.ImageField(upload_to=wiseturn.models.institution_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tuition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.TextField()),
                ('discipline', models.TextField()),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiseturn.Institution')),
            ],
        ),
        migrations.AlterField(
            model_name='wtuser',
            name='uid',
            field=models.CharField(default=wiseturn.models.hex_uuid, max_length=255),
        ),
    ]
