# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import wiseturn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0004_auto_20190123_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='uid',
            field=models.CharField(default=wiseturn.models.hex_uuid, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='uid',
            field=models.CharField(default=wiseturn.models.hex_uuid, max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='founded',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='discipline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
