# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0005_auto_20190204_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='dli_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
