# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0007_auto_20190402_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_status',
            field=models.CharField(choices=[('ACC', 'Accepted Offer'), ('WIT', 'Withdrawn'), ('PEN', 'PENDING')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='applicant_status',
            field=models.CharField(choices=[('ACC', 'Accepted Offer'), ('WIT', 'Withdrawn'), ('PEN', 'PENDING')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='wtuser',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('PEN', 'Pending'), ('REV', 'Under Review'), ('APP', 'Approved'), ('WAI', 'Waitlist'), ('REJ', 'Rejected')], default='SUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('PEN', 'Pending'), ('REV', 'Under Review'), ('APP', 'Approved'), ('WAI', 'Waitlist'), ('REJ', 'Rejected')], default='SUB', max_length=3),
        ),
    ]
