# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0008_auto_20190404_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='scores_citations',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_citations_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_industry_income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_industry_income_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_international_outlook',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_international_outlook_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_overall',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_overall_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_research',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_research_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_teaching',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scores_teaching_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='stats_female_male_ratio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='stats_number_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='stats_pc_intl_students',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='stats_student_staff_ratio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
