# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0009_auto_20190407_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='stats_pc_intl_students',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='stats_student_staff_ratio',
            field=models.FloatField(null=True),
        ),
    ]
