# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-13 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0011_wtuser_interst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtuser',
            old_name='interst',
            new_name='interest',
        ),
    ]
