# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-16 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0008_wtuser_school'),
        ('wiseturn', '0012_auto_20190413_0018'),
    ]

    operations = [
    ]
