# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-20 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0013_wtuser_summary'),
        ('wiseturn', '0014_wtuser_summary'),
    ]

    operations = [
    ]
