# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-20 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import wiseturn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0015_merge_20190420_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtuser',
            name='resume',
            field=models.FileField(null=True, upload_to=wiseturn.models.wtuser_directory_path),
        ),
        migrations.AddField(
            model_name='wtuser',
            name='transcript',
            field=models.FileField(null=True, upload_to=wiseturn.models.wtuser_directory_path),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_status',
            field=models.CharField(choices=[('ACC', 'Accepted Offer'), ('WIT', 'Withdrawn'), ('PEN', 'Pending')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='applicant_status',
            field=models.CharField(choices=[('ACC', 'Accepted Offer'), ('WIT', 'Withdrawn'), ('PEN', 'Pending')], default='PEN', max_length=3),
        ),
    ]
