# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-20 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0015_merge_20190416_1840'),
        ('wiseturn', '0016_auto_20190420_0329'),
    ]

    operations = [
    ]
