# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import wiseturn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0017_merge_20190420_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtuser',
            name='profilepic',
            field=models.ImageField(null=True, upload_to=wiseturn.models.wtuser_directory_path),
        ),
    ]
