# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-24 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wiseturn.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiseturn', '0018_wtuser_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=wiseturn.models.hex_uuid, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiseturn.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
